### ISSUE TITLE
Using python module arlpy in golang simulation?

### ISSUE THREAD

**Issue by Vytek** [cpunion/go-python#7]
Congratulations for this interesting library. I am trying to understand, is it possible to use it to use a properly configured python module arlpy from golang application on linux:

https://arlpy.readthedocs.io/en/latest/uwapm.html

The application should call:

```
>>> import arlpy.uwapm as pm
>>> env = pm.create_env2d()
>>> tloss = pm.compute_transmission_loss(env, mode=pm.incoherent)
>>> pm.plot_transmission_loss(tloss, width=1000)

```
https://github.com/org-arl/arlpy

**Comment by cpunion** [comment]
@Vytek I just tested, seems it worked, but something wrong in above code.

```shell
(py312) ➜  go-python git:(fix) ✗ python
Python 3.12.3 | packaged by Anaconda, Inc. | (main, May  6 2024, 14:46:42) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import arlpy.uwapm as pm
>>> env = pm.create_env2d()
>>> tloss = pm.compute_transmission_loss(env, mode=pm.incoherent)
[WARN] Bellhop did not generate expected output file
>>> pm.plot_transmission_loss(tloss, width=1000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lijie/miniforge3/envs/py312/lib/python3.12/site-packages/arlpy/uwapm.py", line 523, in plot_transmission_loss
    xr = (min(tloss.columns), max(tloss.columns))
              ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'columns'
```

The go-python version:

```go
package main

import gp "github.com/cpunion/go-python"

func main() {
	gp.Initialize()
	pm := gp.ImportModule("arlpy.uwapm")
	env := pm.Call("create_env2d")
	tloss := pm.Call("compute_transmission_loss", env, gp.KwArgs{"mode": pm.Attr("incoherent")})
	pm.Call("plot_transmission_loss", tloss, gp.KwArgs{"width": 1000})
}
```

Build and run:

```shell
(py312) ➜  go-python git:(fix) ✗ go build -o arlpy.out ./_demo/arlpy && ./arlpy.out
[WARN] Bellhop did not generate expected output file
Traceback (most recent call last):
  File "/Users/lijie/miniforge3/envs/py312/lib/python3.12/site-packages/arlpy/uwapm.py", line 523, in plot_transmission_loss
    xr = (min(tloss.columns), max(tloss.columns))
              ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'columns'
```

It has same outputs to your Python code.

**Comment by cpunion** [comment]
@Vytek Could you please share me why do you need call this library in Go? I wish `go-python` more useful.

**Comment by Vytek** [comment]
Of course and with pleasure. There is no doubt that the amount of scientific libraries in python is enormous. In this specific case arlpy is the simplest interface that the Ocean mathematical simulation platform that we are developing towards Bellhop Underwater Acoustics:
https://patel999jay.github.io/post/bellhop-acoustic-toolbox/ without having to rewrite the entire library in Go. In addition, the new version https://github.com/A-New-BellHope/bellhopcuda is also written in C++ and it is not at all easy to interface it in Go. Going through arlpy everything is much simpler and tested and I believe that this is true for many other scientific contexts.

**Comment by cpunion** [comment]
Thank you for sharing, this is similar to what I had in mind. There are many libraries that don't have Go bindings, or only have old and incomplete versions, while Python has many better wrappers of these libraries.

**Comment by Vytek** [comment]
> Owner

Perfect, I will use this same system to interface with many other scientific libraries that have excellent management on python.

As for the anomaly that you reported to me, it is most likely due to the installation of the Bellhope binary that must be done separately before the relative wrapper in python. In any case, I am experimenting. Thank you very much for everything!
